services:
  denolith_api:
    build: .
    restart: always
    ports:
      - "9999:3000"
    environment:
      # Cấu hình chung
      - PORT=3000
      - DENO_ENV=production
      - DATABASE_URL=postgres://postgres:postgres@db:5432/denolith?schema=public
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=example_secret_co_do_dai_32ky_tu # Tạo secret ngẫu nhiên >= 32 ký tự. Ví dụ: openssl rand -hex 32
      # Cấu hình CORS & Security
      - FRONTEND_URL=http://localhost:5173
      - TRUST_PROXY=false
      # Cấu hình Gửi Mail SMTP (Optional)
      - SMTP_HOST=smtp.resend.com
      - SMTP_PORT=587
      - SMTP_USER=resend
      - SMTP_PASS=re_123456789
      - SMTP_FROM=noreply@denolith.dev
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:18-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: denolith
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.4-alpine
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
