global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "prometheus-alert-rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "denolith-api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["host.docker.internal:9999"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
